# Screen settings
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

# Tiles settings
TILE_SIZE = 40

# Player settings
PLAYER_WIDTH = TILE_SIZE * 0.8
PLAYER_HEIGHT = TILE_SIZE * 0.95
PLAYER_GRAVITY = 0.8
PLAYER_JUMP_STRENGTH = -17
PLAYER_SPEED = 8
