[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neural-jump"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy==2.5.2",
    "pygame-ce==2.5.8",
    "torch==2.13.0",
]

[tool.setuptools.packages.find]
include = ["ai", "game"]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
